Change too generic function name
This breaks ZTS build on Linux

/dev/shm/BUILD/php-pecl-couchbase-1.2.1/ZTS/replica.c:32:22: error: conflicting types for 'clone'
 static struct entry *clone(lcb_error_t error, const lcb_get_resp_t *r) {
                      ^
In file included from /usr/include/sched.h:42:0,
                 from /usr/include/pthread.h:23,
                 from /usr/include/php-zts/php/Zend/../TSRM/TSRM.h:55,
                 from /usr/include/php-zts/php/Zend/zend_alloc.h:27,
                 from /usr/include/php-zts/php/Zend/zend.h:252,
                 from /usr/include/php-zts/php/main/php.h:34,
                 from /dev/shm/BUILD/php-pecl-couchbase-1.2.1/ZTS/internal.h:49,
                 from /dev/shm/BUILD/php-pecl-couchbase-1.2.1/ZTS/replica.c:18:
/usr/include/bits/sched.h:82:12: note: previous declaration of 'clone' was here
 extern int clone (int (*__fn) (void *__arg), void *__child_stack,
            ^

Change-Id: I17cde28944e87b72c08718be8078097f1927f172
Reviewed-on: http://review.couchbase.org/29367
Reviewed-by: Trond Norbye <trond.norbye@gmail.com>
Reviewed-by: Mark Nunberg <mnunberg@haskalah.org>
Tested-by: Trond Norbye <trond.norbye@gmail.com>